import type { ProductAnalysis } from '@/types/analysis';

export const DEMO_PRODUCT_ANALYSIS = {
  schemaVersion: 1,
  source: 'combined',
  product: {
    name: 'Wholegrain Cocoa, Almond & Cranberry Breakfast Squares — Family Recipe Edition',
    brand: 'Pantry Field',
    barcode: '8901234567890',
    servingSize: '1 square (45 g)',
  },
  verdict: {
    value: 'okay_in_moderation',
    title: 'Okay in moderation',
    shortReason: 'It provides some fiber and protein, but the photographed serving is also fairly high in sugar.',
    confidence: 'high',
  },
  calories: {
    perServingKcal: 210,
    per100gKcal: 467,
  },
  nutrition: {
    protein: { value: 6, unit: 'g' },
    carbohydrates: { value: 29, unit: 'g' },
    sugars: { value: 12, unit: 'g' },
    fat: { value: 8, unit: 'g' },
    saturatedFat: { value: 2.5, unit: 'g' },
    fiber: { value: 4, unit: 'g' },
    sodium: { value: 180, unit: 'mg' },
    salt: { value: null, unit: null },
  },
  ingredients: {
    rawText:
      'Wholegrain rolled oats (34%), whole wheat flour, dried cranberries (cranberries, cane sugar, sunflower oil), almonds (8%), cocoa powder, brown rice syrup, chicory root fiber, sunflower oil, skimmed milk powder, cocoa butter, sea salt, sunflower lecithin, natural vanilla flavor, mixed tocopherols.',
    items: [
      {
        name: 'Wholegrain rolled oats (34%)',
        normalizedName: 'Rolled oats',
        explanation: 'A whole grain that contributes carbohydrate and fiber.',
        category: 'fiber',
        concernLevel: 'none',
        evidence: 'Listed first and identified as 34% of the product.',
      },
      {
        name: 'Whole wheat flour',
        normalizedName: 'Whole wheat flour',
        explanation: 'Ground whole wheat used to give the square structure.',
        category: 'common_food',
        concernLevel: 'none',
        evidence: 'Listed on the photographed package.',
      },
      {
        name: 'Dried cranberries',
        normalizedName: 'Sweetened dried cranberries',
        explanation: 'Dried fruit prepared here with added cane sugar and sunflower oil.',
        category: 'common_food',
        concernLevel: 'low',
        evidence: 'The sub-ingredients name cane sugar and sunflower oil.',
      },
      {
        name: 'Almonds (8%)',
        normalizedName: 'Almonds',
        explanation: 'A tree nut that contributes fat, protein, and texture.',
        category: 'allergen',
        concernLevel: 'none',
        evidence: 'The label identifies almonds as 8% of the product.',
      },
      {
        name: 'Cocoa powder',
        normalizedName: 'Cocoa powder',
        explanation: 'Cocoa solids used for chocolate flavor and color.',
        category: 'flavor',
        concernLevel: 'none',
        evidence: 'Listed on the photographed package.',
      },
      {
        name: 'Brown rice syrup',
        normalizedName: 'Brown rice syrup',
        explanation: 'A concentrated syrup used mainly to sweeten and bind ingredients.',
        category: 'sugar',
        concernLevel: 'moderate',
        evidence: 'The nutrition panel reports 12 g sugars per serving.',
      },
      {
        name: 'Chicory root fiber',
        normalizedName: 'Chicory root fiber',
        explanation: 'A plant-derived fiber that can also help with texture.',
        category: 'fiber',
        concernLevel: 'none',
        evidence: 'Listed on the photographed package.',
      },
      {
        name: 'Sunflower oil',
        normalizedName: 'Sunflower oil',
        explanation: 'A vegetable oil used for moisture and texture.',
        category: 'fat_or_oil',
        concernLevel: 'low',
        evidence: 'Listed on the photographed package.',
      },
      {
        name: 'Skimmed milk powder',
        normalizedName: 'Skimmed milk powder',
        explanation: 'Dried milk solids that add flavor and protein.',
        category: 'allergen',
        concernLevel: 'none',
        evidence: 'Milk is also named in the declared allergen statement.',
      },
      {
        name: 'Sunflower lecithin',
        normalizedName: 'Sunflower lecithin',
        explanation: 'An emulsifier that helps fat and other ingredients stay mixed.',
        category: 'additive',
        concernLevel: 'none',
        evidence: 'Listed on the photographed package.',
      },
      {
        name: 'Natural vanilla flavor',
        normalizedName: 'Natural vanilla flavor',
        explanation: 'A flavoring used to add a vanilla note.',
        category: 'flavor',
        concernLevel: 'unknown',
        evidence: 'The label does not provide a more detailed composition.',
      },
      {
        name: 'Mixed tocopherols',
        normalizedName: 'Tocopherols',
        explanation: 'Antioxidants used to help slow oxidation and preserve freshness.',
        category: 'preservative',
        concernLevel: 'none',
        evidence: 'Listed on the photographed package.',
      },
    ],
  },
  allergens: {
    declared: ['Milk', 'Almonds', 'Wheat'],
    traces: ['Peanuts', 'Soy'],
    statement: 'Contains milk, almonds and wheat. May contain peanuts and soy.',
  },
  labelSignals: {
    nutriScore: 'C',
    novaGroup: 4,
    nutrientLevels: {
      fat: 'moderate',
      saturatedFat: 'moderate',
      sugar: 'high',
      salt: 'low',
    },
    additives: ['Sunflower lecithin', 'Mixed tocopherols'],
  },
  positives: ['4 g fiber per serving', '6 g protein per serving', 'Wholegrain oats are the first ingredient'],
  concerns: ['12 g sugar per serving', 'Contains three declared allergens', 'Serving size matters for calories'],
  dataQuality: {
    confidence: 'high',
    missingFields: ['Salt value'],
    warnings: ['Open Food Facts listed an older serving size; photographed label values were used.'],
  },
  disclaimer:
    'For general informational use, not medical advice. Product recipes can change. Verify the physical package and manufacturer information, especially if you have a severe allergy.',
} satisfies ProductAnalysis;
